spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: spring
    password: Spring123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    include:
      - security

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true